### ISSUE TITLE
[`symmetry`]: `/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found`

### ISSUE THREAD

**Issue by calvinp0** [ReactionMechanismGenerator/conda-recipes#19]
### Topic
General area which your question is related to.
 - [X] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

### Context & Question
Hi RMG team,

I noticed that the `symmetry` packages was updated just over a month ago. However, the previous version of it has been erased from the rmg conda channel. So,  I am hoping that someone has the older version of symmetry. The reason being is that we use RMG on Ubuntu 20.04 and CentOS 8.10 (Rocky) and when we have installed the RMG environment or new users, we receive an error

```bash
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by symmetry)
```

So, from my understanding, `symmetry` now requires GLIBC 2.34 since the update

**Comment by mjohnson541** [comment]
It doesn't look like at least all the old binaries were erased, unless there was something between the 8 year old 32-bit ones and the month old ones or maybe there were old 64-bit ones? The build number was the same for the new ones so it's possible that led to overwriting.  

Immediately you might be able to use the binaries from: https://anaconda.org/connie/symmetry where some of thee binaries were copied from. The ones there might be your missing ones if you're missing 8-year old 64-bit ones. 

@rwest @JacksonBurns did one of you guys upload new symmetry binaries?

**Comment by rwest** [comment]
Perhaps this workflow overwrote things? (as you say, the build number seems to not be incremented)
https://github.com/ReactionMechanismGenerator/conda-recipes/actions 

I like the suggestion of using connie's binaries. (`conda uninstall symmetry; conda install -c connie symmetry`). When she built it in 2015 GLIBC was on version 2.21.

Might be nice to increment the build on the new one, and get the old one back?
(Or somehow make a newer one backwards compatible?)

**Comment by JacksonBurns** [comment]
@calvinp0 would `sudo apt install glibc` help with this?

And yes, the old binary was overwritten when the `conda-recipes` repo was overhauled - my apologies.

We can copy the `connie` channel's binary back on to `rmg` and re-upload the latest versions under a different version or build number.

FWIW, I changed nothing about the recipe when doing the overhaul, so I am rather confused. I _think_ the issue comes from [this line in the symmetry source code](https://github.com/connie/symmetry/blob/master/symmetry.c#L33) which instructs the compiler to link the binary against the math library, which has perhaps been removed from the standard library in current compiler world but was not at the time.

We should treat this as a bug with the `symmetry` recipe - I will transfer this issue to `conda-recipes`.

**Comment by calvinp0** [comment]
> @calvinp0 would `sudo apt install glibc` help with this?
> 
> And yes, the old binary was overwritten when the `conda-recipes` repo was overhauled - my apologies.
> 
> We can copy the `connie` channel's binary back on to `rmg` and re-upload the latest versions under a different version or build number.
> 
> FWIW, I changed nothing about the recipe when doing the overhaul, so I am rather confused. I _think_ the issue comes from [this line in the symmetry source code](https://github.com/connie/symmetry/blob/master/symmetry.c#L33) which instructs the compiler to link the binary against the math library, which has perhaps been removed from the standard library in current compiler world but was not at the time.
> 
> We should treat this as a bug with the `symmetry` recipe - I will transfer this issue to `conda-recipes`.

Hey @JacksonBurns,

Unfortunately I cannot do this for the servers we run RMG on as we do not have `sudo` privileges. And as you can see here, in this output, `glibc` is installed, its just an older version.

```bash
(arc_env) (base) calvin.p@zeus:~/runs/ARC/TS_KeyError/calcs/Species/rxn_3137_p1_[N-]=c1o[nHp]no1/opt_a53624$ ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
``` 

I did attempt to follow the instructions here: https://stackoverflow.com/questions/72513993/how-to-install-glibc-2-29-or-higher-in-ubuntu-18-04

But when I set `glibc` to the `LD_LIBRARY_PATH`, I get a segmentation error. So, it looks like it is a no go unless I am doing something wrong when compiling and setting it in the users `LD_LIBRARY_PATH`.

Anyway, that would be great regarding uploading the older version. I will get back to you guys once I have attempted to install the older version.

**Comment by calvinp0** [comment]
Just to update everyone, I installed symmetry from the `connie` channel and `symmetry` works again on our servers. Thanks everyone!
