### ISSUE TITLE
Anaconda rmg channel for 32-bit linux

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/conda-recipes#4]
I wonder if it would be worth the effort to create a linux 32-bit channel for rmg.

``` bash
vagrant@precise32:~$ conda install -c rmg -y rmg rmgdatabase
Fetching package metadata: ......
Error: No packages found in current linux-32 channels matching: rmg

```

**Comment by nickvandewiele** [comment]
[Here](http://conda.pydata.org/docs/build_tutorials/pkgs2.html#build-and-install) it is explained how to create binaries for all possible platforms.

Simply do:

```
conda convert --platform all /path/to/binary-py27_0.tar.bz2 -o outputdir/
```

will generate the binary and put it in the specified `outputdir`.

The flag `all` will create a binary win32/64, linux32/64, and os-x.

**Comment by rwest** [comment]
Only for pure Python packages iirc. Anything that needs compiling needs compiling on each platform, I think. Maybe you can compile 32 bit on a 64 bit platform, but I don't think you can compile windows on a Mac or Mac on Linux etc

**Comment by nickvandewiele** [comment]
That makes sense.

I've created a binary package for scoop based on the recipe here (https://github.com/ReactionMechanismGenerator/conda-recipes/pull/3), and uploaded that to my user profile (http://anaconda.org/nickvandewiele/scoop). Is there a way to copy (clone) this package to another user on anaconda.org, e.g. RMG?

**Comment by nickvandewiele** [comment]
After one is added as an owner of the organization (RMG) on anaconda.org, one can copy a specific package from your account to the organization you are owner of:

Do this on a local machine (assuming the machine has access to your acount on anaconda.org:

```
anaconda copy username/package/version --to-owner <organization>
```

For example:

```
anaconda copy nickvandewiele/scoop/0.7 --to-owner RMG
```

**Comment by JacksonBurns** [comment]
This issue is stale, and we do not support 32 bit OSs nor intend to in the future. Closing.
